# Site settings
title: Avanish Singh

# User settings
username: Avanish Singh
user_description: Software Engineer, Competitive Programmer, Movie Lover 
github_username: iavanish
quora_username: Avanish-Singh
imdb_username: ur34526391
facebook_username: iavanish 

exclude: ['package.json', 'src' , 'node_modules']
