# Site settings
title: Avanish Singh
description: Personal Website
baseurl: ""
url: "localhost:4000"

# run using exec jekyll serve

# User settings
username: Avanish Singh
user_title: Software Engineer, Competitive Programmer 
email: avanishsingh123@gmail.com
twitter_username: iavanish
github_username: iavanish
gplus_username: 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
